// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjN_LBa6g41MmXt7UYRHmpL1U_HITt6WM',
    appId: '1:867205188923:web:78a53111fa202e6cd13b1e',
    messagingSenderId: '867205188923',
    projectId: 'authentication-858e0',
    authDomain: 'authentication-858e0.firebaseapp.com',
    databaseURL: 'https://authentication-858e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'authentication-858e0.appspot.com',
    measurementId: 'G-XNFDN3Z7KW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7PdmTVO5K-7uha4kA-a-NMkaY2srYOyE',
    appId: '1:867205188923:android:ef2ffeb83e7d6dced13b1e',
    messagingSenderId: '867205188923',
    projectId: 'authentication-858e0',
    databaseURL: 'https://authentication-858e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'authentication-858e0.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjN_LBa6g41MmXt7UYRHmpL1U_HITt6WM',
    appId: '1:867205188923:web:a0712c027b670decd13b1e',
    messagingSenderId: '867205188923',
    projectId: 'authentication-858e0',
    authDomain: 'authentication-858e0.firebaseapp.com',
    databaseURL: 'https://authentication-858e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'authentication-858e0.appspot.com',
    measurementId: 'G-QP0X7TYGEP',
  );
}
